# -*- coding: utf-8 -*-
"""Checkpoint3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CvuCuE_R8aIqE6EVBnon-kkziqbkB94I
"""

# N.B : l'idée dans ma tete n'est pas mise en oeuvre comme je le veux. La prochaine séance merci de montrer comment éviter ce genre de faute pour que je puisse avancer. Merci

#Question 1

def maximum(a, b, c):
    list = [a, b, c]
    return max(list)

a = 10
b = 14
c = 12
print(maximum(a, b, c))

#Question 2

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

x=50
y=25

res = calculation(50,25)
print(res)

#Question 3

def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total
print(sum((18, 32, -3, 0, 7)))

def multiply(numbers):  
    total = 1
    for x in numbers:
        total *= x  
    return total  
print(multiply((18, 32, -3, 0, 7)))

#Question 4

print(green,red,yellow,black,white)
lst=[n for n in raw_input().split('-')]  
lst.sort()
print("Sorted:")
print('-'.join(lst))

